---
- include_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: /etc/sysctl.conf | Set swappiness to 1
  sysctl:
    name: "{{item.name}}"
    value: "{{item.value}}"
    state: present
    sysctl_set: yes
  with_items:
    - {name: vm.swappiness,     value: 1        }
    - {name: vm.max_map_count,  value: 262144   }
    - {name: fs.file-max,       value: 262144   }
  tags: setup
