---
- name: Install yum-utils
  yum: name=yum-utils state=present

- name: Execute yum-complete-transaction
  shell: yum-complete-transaction --cleanup-only

- name: Install Base Packages
  yum:
    name: "{{item}}"
    state: installed
    update_cache: yes
  with_items:
    - wget
    - lsof
    - vim
    - nc
    - net-tools
    - java-1.8.0-openjdk

- name: SELinux | getenforce register
  shell: getenforce
  register: sestatus

- name: SELinux | disable
  selinux: state=disabled

- name: SELinux | setenforce 0 if not disabled
  command: setenforce 0
  when: sestatus.stdout == "Enforce"

- name: Repository | Import GPG KEY 
  rpm_key:
    state: present
    key: "{{es_rpm_key}}"

- name: Repository | Copying file elasticsearch.repo to /etc/yum.repos.d/ 
  template:
    src: elasticsearch.repo.j2
    dest: "/etc/yum.repos.d/elasticsearch-{{es_major_version}}.repo"
    owner: root
    group: root
    mode: 0644
