---
- name: Create Directories
  file: path={{ item }} state=directory owner={{ es_user }} group={{ es_group }}
  with_items:
    - "{{log_dir}}"

- name: Create Data Directories
  file: path={{ item }} state=directory owner={{ es_user }} group={{ es_group }}
  with_items:
    - "{{es_datadirs}}"

- name: Copy Configuration File - elasticsearch.yml
  template: 
    src: elasticsearch.yml.j2 
    dest: "{{es_conf_dir}}/elasticsearch.yml" 
    owner: "{{ es_user }}" 
    group: "{{ es_group }}" 
    mode: 0644 
    force: yes
  register: system_change
  notify: restart elasticsearch

- name: Copy log4j2.properties File for Instance
  template: 
    src: log4j2.properties.j2  
    dest: "{{es_conf_dir}}/log4j2.properties" 
    owner: "{{ es_user }}" 
    group: "{{ es_group }}" 
    mode: 0644 
    force: yes
  notify: restart elasticsearch

- name: Copy jvm.options File for Instance
  template: 
    src: jvm.options.j2 
    dest: "{{es_conf_dir}}/jvm.options" 
    owner: "{{ es_user }}" 
    group: "{{ es_group }}" 
    mode: 0644 
    force: yes
  notify: restart elasticsearch
