---
##- name: ElasticSearch | /etc/security/limits.conf
##  pam_limits:
##    domain: "{{item.domain}}"
##    limit_type: "{{item.limit_type}}"
##    limit_item: "{{item.limit_item}}"
##    value: "{{item.value}}"
##  with_items:
##    - {domain: "{{es_user}}", limit_type: soft, limit_item: nofile, value: 64000 }
##    - {domain: "{{es_user}}", limit_type: soft, limit_item: nproc,  value: 64000 }
##    - {domain: "{{es_user}}", limit_type: hard, limit_item: nofile, value: 64000 }
##    - {domain: "{{es_user}}", limit_type: hard, limit_item: nproc,  value: 64000 }
##  tags: limits
##
##- include_tasks: RedHat.yml
##  when: ansible_os_family == 'RedHat'
##
##- include_tasks: config.yml

- include_tasks: x-pack.yml
  when: es_install_x-pack == 'true'

- name: ElasticSearch | Start and enable service
  service:
    name: "{{es_service_name}}"
    state: "{{es_service_state}}"
    enabled: "{{es_service_enabled}}"
