---
- name: Instalando os pre-requisitos
  hosts: all
  roles:
    - roles/common

- name: Install ElasticSearch 
  hosts: elasticsearch-masternode
  roles:
    - { role: roles/elasticsearch, es_instance_name: "node1",
    es_config: {
        cluster.name: "elastichurrops",
        http.port: 9200,
        transport.tcp.port: 9300,
        bootstrap.memory_lock: false,
        }
    }
  vars: 
    es_plugins:
      - plugin: ingest-geoip
      - plugin: x-pack
