---
- name: Instalando os pre-requisitos
  hosts:
    - elasticsearch-masternode
    - elasticsearch-datanode
  roles:
    - roles/common

- name: Install ElasticSearch 
  hosts: elasticsearch-masternode
  roles:
    - { role: "roles/elasticsearch", es_instance_name: "masternode",
    es_config: {
        cluster.name: "neo-elasticsearch-apm",
        http.port: 9200,
        transport.tcp.port: 9300,
        bootstrap.memory_lock: false,
        }
    }

- name: Install ElasticSearch
  hosts: elasticsearch-datanode
  roles:
    - { role: "roles/elasticsearch", es_instance_name: "datanode",
    es_config: {
        cluster.name: "neo-elasticsearch-apm",
        http.port: 9200,
        transport.tcp.port: 9300,
        bootstrap.memory_lock: false,
        }
    }
