---
- name: Kibana | Copying kibana.yml
  template:
    src: kibana.yml.j2
    dest: "/etc/kibana/kibana.yml"
    force: yes
  notify: kibana restart

- name: Kibana | Ensure started and enable
  service:
    name: "kibana"
    state: started
    enabled: yes
