---
# group_vars/elastic

- name: Elastic | Ensure dependencies are installed.
  package: name="{{item}}" state=present
  with_items:
    - lsof
    - wget
    - vim
  tags: elastic

- name: Elastic | Ensure Elastic Group
  group: 
    name: "{{elastic_group}}"
  tags: elastic

- name: Elastic | Ensure Elastic User
  user:
    name: "{{elastic_user}}"
    group: "{{elastic_group}}"
    home: "/home/{{elastic_user}}"
    createhome: yes
  tags: elastic

- name: Elastic | Extract Package
  unarchive:
    src: "{{elastic_get_url}}"
    dest: "{{elastic_install_dir}}"
    owner: "{{elastic_user}}"
    group: "{{elastic_group}}"
    remote_src: yes
    creates: "{{elastic_install_dir}}/elastic-{{elastic_version}}/bin/elastic"
  tags: elastic

- name: Elastic | Create symbol link
  file:
    src: "{{elastic_install_dir}}/elastic-{{elastic_version}}"
    dest: "{{elastic_install_dir}}/{{elastic_inst_name}}"
    state: link
    force: yes
  tags: elastic

- name: Elastic | Ensure Elastic dirs exists
  file:
    path: "{{item}}"
    state: directory
    owner: "{{elastic_user}}"
    group: "{{elastic_group}}"
  with_items:
    - "{{ elastic_logDir }}"
    - "{{ elastic_dataDir }}"
  tags: elastic
