---
- name: Logstash | Copy logstash.yml to /etc/logstash.yml
  template:
    src: logstash.yml.j2
    dest: "/etc/logstash/logstash.yml"
    owner: "{{ls_user}}"
    group: "{{ls_group}}"
    mode: "755"
  notify: restart logstash
