---
- name: Logstash | Install Package
  yum:
    name: "{{ls_user}}"
    state: "{{ls_group}}"

- name: Logstash | Start and enable service
  service:
    name: "{{ls_service_name}}"
    state: "{{ls_service_name}}"
    enabled: "{{yes}}"
